- Move M4 code into m4 subdir and get it from external repository. - Update local logger objects path (../logger/src). - Update logger URL (/projects/ prefix).
git-svn-id: https://oops.math.spbu.ru/svn/settings/trunk@33 8fa8552c-3af7-0310-8def-ec619170fbba

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -799,6 +799,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --without-findlib       do not use findlib package system
+  --with-ocamldsort       sort sources before build
   --with-sitelib=DIR      specify OCaml installation directory
 
 _ACEOF
@@ -2155,11 +2156,15 @@ fi
 	{ echo "$as_me:$LINENO: WARNING: Cannot find OCaml C compiler ($OCAMLCC); bytecode compilation only" >&5
 echo "$as_me: WARNING: Cannot find OCaml C compiler ($OCAMLCC); bytecode compilation only" >&2;}
 	unset OCAMLOPT
-    else
-	CC=$OCAMLC
-	touch conftest.ml
-	ac_ext=ml
-	# Try to create an executable without -o first, disregard a.out.
+    fi
+    rm -f conftest.c
+fi
+
+CC=$OCAMLC
+touch conftest.ml
+ac_ext=ml
+ac_link="$CC conftest.ml && ( rm -f conftest.cm?; test -f camlprog.exe && mv camlprog.exe a.exe || true )"
+# Try to create an executable without -o first, disregard a.out.
 # It will help us diagnose broken compilers, and finding out an intuition
 # of exeext.
 echo "$as_me:$LINENO: checking for C compiler default output file name" >&5
@@ -2217,7 +2222,7 @@ ac_exeext=$ac_cv_exeext
 echo "$as_me:$LINENO: result: $ac_file" >&5
 echo "${ECHO_T}$ac_file" >&6
 
-	# Check the compiler produces executables we can run.  If not, either
+# Check the compiler produces executables we can run.  If not, either
 # the compiler is broken, or we cross compile.
 echo "$as_me:$LINENO: checking whether the C compiler works" >&5
 echo $ECHO_N "checking whether the C compiler works... $ECHO_C" >&6
@@ -2248,7 +2253,7 @@ fi
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
-	echo "$as_me:$LINENO: checking for suffix of executables" >&5
+echo "$as_me:$LINENO: checking for suffix of executables" >&5
 echo $ECHO_N "checking for suffix of executables... $ECHO_C" >&6
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
@@ -2281,10 +2286,9 @@ rm -f conftest$ac_cv_exeext
 echo "$as_me:$LINENO: result: $ac_cv_exeext" >&5
 echo "${ECHO_T}$ac_cv_exeext" >&6
 
-	rm -f a.out
-	EXEEXT=$ac_cv_exeext
-    fi
-fi
+rm -f a.out a.exe
+EXEEXT=$ac_cv_exeext
+
 
 
 BFLAGS='$(AM_BFLAGS)'
@@ -2671,7 +2675,14 @@ else
   OCAMLFIND_FALSE=
 fi
 
-# Extract the first word of "ocamldsort", so it can be a program name with args.
+
+# Check whether --with-ocamldsort or --without-ocamldsort was given.
+if test "${with_ocamldsort+set}" = set; then
+  withval="$with_ocamldsort"
+  use_ocamldsort="$withval"
+fi;
+if test "$use_ocamldsort" = yes; then
+	# Extract the first word of "ocamldsort", so it can be a program name with args.
 set dummy ocamldsort; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -2707,12 +2718,15 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test "$have_ocamldsort" = no; then
-    { echo "$as_me:$LINENO: WARNING: Cannot find ocamldsort, using echo" >&5
+	if test "$have_ocamldsort" = no; then
+	    { echo "$as_me:$LINENO: WARNING: Cannot find ocamldsort, using echo" >&5
 echo "$as_me: WARNING: Cannot find ocamldsort, using echo" >&2;}
-    OCAMLDSORT=echo
+	    OCAMLDSORT=echo
+	else
+	    OCAMLDSORT=ocamldsort
+	fi
 else
-    OCAMLDSORT=ocamldsort
+	OCAMLDSORT=echo
 fi
 
 
@@ -2752,9 +2766,9 @@ echo "${ECHO_T}adding $check_inc" >&6
     fi
     if ! test "$found"; then
 	if test "$SITELIBDIR" != ""; then
-	    dirs="+camlp4 ../logger $SITELIBDIR/logger"
+	    dirs="+camlp4 ../logger/src $SITELIBDIR/logger"
 	else
-	    dirs="+camlp4 ../logger"
+	    dirs="+camlp4 ../logger/src"
 	fi
 	for check_dir in $dirs; do
 	    builddir=`pwd`
@@ -2765,12 +2779,6 @@ echo "${ECHO_T}adding $check_inc" >&6
 	    if $CAMLP4R -I $check_dir conftest.ml > /dev/null 2>&1 ; then
 		found=yes
 		break
-	    else
-		check_dir=$check_dir/src
-		if $CAMLP4R -I $check_dir conftest.ml > /dev/null 2>&1 ; then
-		    found=yes
-		    break
-		fi
 	    fi
 	done
 	if test "$found" ; then
@@ -2780,9 +2788,9 @@ echo "${ECHO_T}adding -I $check_dir" >&6
 	else
 	    echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
-	    if ! test -z "http://oops.tepkom.ru/logger"; then
-		{ echo "$as_me:$LINENO: WARNING: Please, visit http://oops.tepkom.ru/logger" >&5
-echo "$as_me: WARNING: Please, visit http://oops.tepkom.ru/logger" >&2;}
+	    if ! test -z "http://oops.tepkom.ru/projects/logger"; then
+		{ echo "$as_me:$LINENO: WARNING: Please, visit http://oops.tepkom.ru/projects/logger" >&5
+echo "$as_me: WARNING: Please, visit http://oops.tepkom.ru/projects/logger" >&2;}
 	    fi
 	    { { echo "$as_me:$LINENO: error: Required module logger not found" >&5
 echo "$as_me: error: Required module logger not found" >&2;}
@@ -2859,6 +2867,10 @@ echo "${ECHO_T}$result" >&6
     else
 		echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
+		if ! test -z ""; then
+		    { echo "$as_me:$LINENO: WARNING: Please, visit " >&5
+echo "$as_me: WARNING: Please, visit " >&2;}
+		fi
 		{ { echo "$as_me:$LINENO: error: Required module $module not found in library str" >&5
 echo "$as_me: error: Required module $module not found in library str" >&2;}
    { (exit 1); exit 1; }; }
